name: Visit Callback Notifier

on:
  schedule:
    # Every 15 min (GitHub cron uses UTC)
    - cron: "*/5 * * * *"
  workflow_dispatch: {}   # manual run button

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2:amd64 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2
      - name: Install Python deps & browsers
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          
      - name: Run notifier
        env:
          VISIT_USERNAME: ${{ secrets.MIS_USERNAME }}
          VISIT_PASSWORD: ${{ secrets.MIS_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          FUTURE_MIN: 15              # how far **ahead**
          LOOKBACK_HOURS: 10          # how far **behind**
        run: python visitcb.py
